# Generated by Django 4.2.30 on 2026-05-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.JSONField()),
            ],
            options={
                'db_table': 'blog_config',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(default='📁', max_length=10)),
                ('score_thresholds', models.JSONField(default=dict, help_text='分档范围，如 {"low": [1,3], "mid": [4,6], "high": [7,10]}')),
                ('article_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'blog_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FailedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('reason', models.CharField(max_length=200)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog_failed_url',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('weight', models.FloatField(default=1.0)),
            ],
            options={
                'db_table': 'blog_score_dimension',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RSSSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('fetch_interval', models.IntegerField(default=3600, help_text='抓取间隔（秒）')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_blog.category')),
            ],
            options={
                'db_table': 'blog_rss_source',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('done', '已完成'), ('failed', '获取失败'), ('unparsable', '无法解析')], default='pending', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('source_name', models.CharField(default='', max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('key_points', models.TextField(blank=True, default='')),
                ('deep_analysis', models.TextField(blank=True, default='')),
                ('raw_html', models.TextField(blank=True, default='')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_blog.category')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_blog.rsssource')),
            ],
            options={
                'db_table': 'blog_article',
                'ordering': ['-created_at'],
            },
        ),
    ]
